name = "sk-diamond-v148"
compatibility_date = "2023-06-28"
compatibility_flags = ["nodejs_compat"]

[build]
command = "bash build.sh"
output_dir = "out"

[site]
bucket = "./out"

[env.production]
pages_build_output_dir = "out"
